"""empty message

Revision ID: af97f75075dd
Revises: 71b43e182fee
Create Date: 2022-05-10 01:16:26.242852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af97f75075dd'
down_revision = '71b43e182fee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('population', sa.String(length=120), nullable=False),
    sa.Column('surface_water', sa.String(length=120), nullable=False),
    sa.Column('terrain', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('classification', sa.String(length=120), nullable=False),
    sa.Column('language', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=False),
    sa.Column('length', sa.String(length=120), nullable=False),
    sa.Column('crew', sa.String(length=120), nullable=False),
    sa.Column('passengers', sa.String(length=120), nullable=False),
    sa.Column('vehicle_class', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.drop_index('name', table_name='Vehicles')
    op.drop_index('name_2', table_name='Vehicles')
    op.drop_table('Vehicles')
    op.drop_index('name', table_name='Species')
    op.drop_index('name_2', table_name='Species')
    op.drop_table('Species')
    op.drop_index('name', table_name='Planets')
    op.drop_index('name_2', table_name='Planets')
    op.drop_table('Planets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Planets',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('population', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('surface_water', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('terrain', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name_2', 'Planets', ['name'], unique=False)
    op.create_index('name', 'Planets', ['name'], unique=False)
    op.create_table('Species',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('classification', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('language', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name_2', 'Species', ['name'], unique=False)
    op.create_index('name', 'Species', ['name'], unique=False)
    op.create_table('Vehicles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('manufacturer', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('length', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('crew', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('passengers', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('vehicle_class', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name_2', 'Vehicles', ['name'], unique=False)
    op.create_index('name', 'Vehicles', ['name'], unique=False)
    op.drop_table('vehicles')
    op.drop_table('species')
    op.drop_table('planets')
    # ### end Alembic commands ###
