"""empty message

Revision ID: d121e9fea492
Revises: 79b9cbd93a8a
Create Date: 2022-05-10 00:41:52.340988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd121e9fea492'
down_revision = '79b9cbd93a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('population', sa.String(length=120), nullable=False),
    sa.Column('surface_water', sa.String(length=120), nullable=False),
    sa.Column('terrain', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('population'),
    sa.UniqueConstraint('population'),
    sa.UniqueConstraint('surface_water'),
    sa.UniqueConstraint('surface_water'),
    sa.UniqueConstraint('terrain'),
    sa.UniqueConstraint('terrain'),
    sa.UniqueConstraint('url'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Planets')
    # ### end Alembic commands ###
