"""empty message

Revision ID: d325cde4b144
Revises: af97f75075dd
Create Date: 2022-05-10 22:53:18.659376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd325cde4b144'
down_revision = 'af97f75075dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('climate', sa.String(length=120), nullable=False))
    op.add_column('planets', sa.Column('rotation', sa.String(length=120), nullable=False))
    op.add_column('planets', sa.Column('orbit', sa.String(length=120), nullable=False))
    op.add_column('planets', sa.Column('diameter', sa.String(length=120), nullable=False))
    op.add_column('planets', sa.Column('imgurl', sa.String(length=120), nullable=False))
    op.drop_column('planets', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('url', mysql.VARCHAR(length=120), nullable=False))
    op.drop_column('planets', 'imgurl')
    op.drop_column('planets', 'diameter')
    op.drop_column('planets', 'orbit')
    op.drop_column('planets', 'rotation')
    op.drop_column('planets', 'climate')
    # ### end Alembic commands ###
